### PR TITLE
Make the RUNTIME-PREFIX patches compatible with Windows

### PR DESCRIPTION
**Pull request by dscho**
It is ironic that the patches trying to port Git for Windows' RUNTIME_PREFIX feature to the broader world require so much care to keep things working on Windows, but there you are: a couple of fixes required to accommodate building Git in Git for Windows' SDK.

I designed the commits as fixups, for easy squashing via `git rebase -i --autosquash`.

### CODE REVIEW

**Comment by danjacques** [comment]
Thanks for the fixes and detailed commit messages - I definitely didn't appreciate the quoting nuances. I've incorporated those fixes and force-pushed the branch again for testing.

As this is my first foray into the Git community, I'm not certain as to the best way to credit you for your help. I've added some `Thanks-To` lines in the new patches, since the other tags suggested in [SubmittingPatches](https://github.com/git/git/blob/master/Documentation/SubmittingPatches) seem to indicate stronger endorsement of the patch set on your part; please let me know if this is insufficient or inappropriate.

RE the `config.mak`, when I build for Mac/Linux with `autoconf`, the `config.mak.in` template gets filled in with prefix-rooted `exec_prefix` and `datadir` values, which percolate into those variables. Even when I don't override `prefix`, `autoconf` defaults to `/usr/local`. I'm not sure if there is a better way to override these values, but the current approach seems fairly minimal and targeted. The systems involved are complex enough that I wouldn't be surprised if there is a nuance that I am missing, though.

(Closing b/c force push)

**Comment by dscho** [comment]
> Thanks for the fixes and detailed commit messages

You're welcome!

> As this is my first foray into the Git community

Hopefully it was not too intimidating? (I hear that a lot, and I have to admit that I sometimes skip reading the mailing list when I am already in a bad mood 😛 )

> I'm not certain as to the best way to credit you for your help.

Whatever you decide, I'm fine with it.

> RE the config.mak, when I build for Mac/Linux with autoconf

Ah, see, that's a use case I did not even think of... I always use `make` directly, no `./configure`.

> (Closing b/c force push)

Heh... there is this nice feature on GitHub where you can allow maintainers to "make edits", i.e. push to your own branch. I did that, you could have pushed to my branch and then merged. But it's fine as it is.

**Comment by danjacques** [comment]
> Hopefully it was not too intimidating? (I hear that a lot, and I have to admit that I sometimes skip reading the mailing list when I am already in a bad mood 😛 )

I was pretty nervous when I submitted my first post to the mailing list - it is intimidating approaching the people who build something as prominent as Git! But everyone I've interacted with has been positive, collaborative, patient, and helpful, so it's been a great experience so far.

> Ah, see, that's a use case I did not even think of... I always use make directly, no ./configure.

That's funny - even after burrowing through the `Makefile` during the creation of this patch, it didn't occur to me that this was an option until you mentioned it. It looks like Travis doesn't use `autoconf`, so I think that you are correct and that I can remove those lines from the testing `config.mak`.

> Heh... there is this nice feature on GitHub where you can allow maintainers to "make edits", i.e. push to your own branch. I did that, you could have pushed to my branch and then merged. But it's fine as it is.

I've been editing/rebasing a chain of dependent branches locally so that I can use `git format-patch` for submission, but I have also not done any GitHub collaboration on this patch set yet, so I don't really have a strong workflow there. I'll try your idea next time if you have any further patches.

**Comment by sunshineco** [comment]
> As this is my first foray into the Git community, I'm not certain as to the best way to credit you for your help. I've added some Thanks-To lines in the new patches...

On the Git project, it's common to do this with `Helped-by:` footers.

**Pull request closed without merging**
